version: '3.7'

services:
  server:
    #build: ./server
    build:
      context: .
      dockerfile: ./server/Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./server/logs:/app/logs
    depends_on:
      - loki
      - grafana
      - rabbitmq # OK ?

  loki:
    image: grafana/loki:latest
    ports:
      - "3100:3100"
    volumes:
      - ./observability/loki/config:/etc/loki
      - ./observability/loki/data:/loki
      - ./observability/loki/wal:/wal
    command: -config.file=/etc/loki/loki-config.yaml

  promtail:
    image: grafana/promtail:latest
    volumes:
      - ./server/logs:/app/logs
      - ./observability/promtail/config:/etc/promtail
    command: -config.file=/etc/promtail/promtail-config.yaml

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3001:3000"
    volumes:
      - ./observability/grafana/data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - loki

  rabbitmq:
    image: rabbitmq:latest
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ./rabbitmq/data:/var/lib/rabbitmq
      #TODO - ./rabbitmq/logs:/var/log/rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
      - RABBITMQ_URI=amqp://guest:guest@localhost:5672/
#    healthcheck:
#      test: [ "CMD", "rabbitmq-diagnostics", "-q", "ping" ]
#      interval: 30s
#      timeout: 10s
#      retries: 5