cameras:
  - name: "tapo C200"
    streamURL: "rtsp://tapoadmin:tapoadmin@192.168.0.99:554/stream1"
    segment_time: 10

  - name: "mock_camera"
    streamURL: "rtsp://mock_camera:8554/live"
    segment_time: 3
