exchanges:
  - name: alerts
    type: topic
    durable: true
    auto_delete: false
    description: "Exchange for alert notifications"
    bindings:
      - queue: alerts.information
        routing_key: "alerts.information.#"
        type: queue
        max_size: 0
        passive: false
        durable: true
        auto_delete: false
        exclusive: false
        no_wait: false
        arguments: { }

      - queue: alerts.warning
        routing_key: "alerts.warning.#"
        type: queue
        max_size: 0
        passive: false
        durable: true
        auto_delete: false
        exclusive: false
        no_wait: false
        arguments: {}

      - queue: alerts.critical
        routing_key: "alerts.critical.#"
        type: queue
        max_size: 0
        passive: false
        durable: true
        auto_delete: false
        exclusive: false
        no_wait: false
        arguments: {}

  - name: videostream
    type: topic
    durable: true
    auto_delete: false
    description: "Exchange for video streaming"
    bindings:
      - queue: videostream.hubid
        routing_key: "videostream.hubid.*"
        type: queue
        max_size: 0
        passive: false
        durable: true
        auto_delete: false
        exclusive: false
        no_wait: false
        arguments: {}

  - name: logs
    type: direct
    durable: true
    auto_delete: false
    description: "Exchange for log messages"
    bindings:
      - queue: logs.warn
        routing_key: logs.warn
        type: queue
        max_size: 0
        passive: false
        durable: true
        auto_delete: false
        exclusive: false
        no_wait: false
        arguments: {}

      - queue: logs.error
        routing_key: logs.error
        type: queue
        max_size: 0
        passive: false
        durable: true
        auto_delete: false
        exclusive: false
        no_wait: false
        arguments: {}

      - queue: logs.info
        routing_key: logs.info
        type: queue
        max_size: 0
        passive: false
        durable: true
        auto_delete: false
        exclusive: false
        no_wait: false
        arguments: {}

  - name: website
    type: topic
    durable: true
    auto_delete: false
    description: "Exchange for website"
    bindings:
      - queue: website.alert
        routing_key: "website.alerts.#"
        type: queue
        max_size: 0
        passive: false
        durable: true
        auto_delete: false
        exclusive: false
        no_wait: false
        arguments: { }