queues:
  - name: mongo-messages
    type: standard
    max_size: 100
    passive: false
    durable: true
    auto_delete: false
    exclusive: false
    no_wait: false
    arguments: { }
    message_format:
      type: json
      schema:
        id: integer           # ID of the sender
        json: string          # The message content
        time_fired: string    # Timestamp of message creation

  - name: hub-warn-logs
    type: standard
    max_size: 100
    passive: false
    durable: true
    auto_delete: false
    exclusive: false
    no_wait: false
    arguments: {}
    message_format:
      type: json
      schema:
          message: string
          time_fired: string
  - name: hub-error-logs
    type: standard
    max_size: 100
    passive: false
    durable: true
    auto_delete: false
    exclusive: false
    no_wait: false
    arguments: {}
    message_format:
      type: json
      schema:
          message: string
          time_fired: string
  - name: hub-info-logs
    max_size: 100
    passive: false
    durable: true
    auto_delete: false
    exclusive: false
    no_wait: false
    arguments: {}
    message_format:
      type: json
      schema:
          message: string
          time_fired: string
  - name: alerts
    max_size: 100
    passive: false
    durable: true
    auto_delete: false
    exclusive: false
    no_wait: false
    arguments: {}
    message_format:
      type: json
      schema:
          message: string
          time_fired: string
