queues:
  - name: mongo-messages
    type: standard
    max_size: 100
    passive: false
    durable: true
    auto_delete: false
    exclusive: false
    no_wait: false
    arguments: { }

  - name: hub-warn-logs
    type: standard
    max_size: 100
    passive: false
    durable: true
    auto_delete: false
    exclusive: false
    no_wait: false
    arguments: {}

  - name: hub-error-logs
    type: standard
    max_size: 100
    passive: false
    durable: true
    auto_delete: false
    exclusive: false
    no_wait: false
    arguments: {}

  - name: hub-info-logs
    max_size: 100
    passive: false
    durable: true
    auto_delete: false
    exclusive: false
    no_wait: false
    arguments: {}
    
  - name: alerts
    max_size: 100
    passive: false
    durable: true
    auto_delete: false
    exclusive: false
    no_wait: false
    arguments: {}

  - name: system_alerts
    max_size: 100
    passive: false
    durable: true
    auto_delete: false
    exclusive: false
    no_wait: false
    arguments: { }

  - name: notifications
    max_size: 100
    passive: false
    durable: true
    auto_delete: false
    exclusive: false
    no_wait: false
    arguments: {}
  - name: notifications_critical
    max_size: 100
    passive: false
    durable: true
    auto_delete: false
    exclusive: false
    no_wait: false
    arguments: {}
exchanges:
  - name: smartess_topic_exchange
    type: topic
    durable: true
    auto_delete: false
    bindings:
      - queue: alerts
        routing_key: "#.alerts.*"
      - queue: system_alerts
        routing_key: "system.alerts.*"
      - queue: notifications
        routing_key: "#.notifications.*"
      - queue: notifications_critical
        routing_key: "#.notifications.critical.*"
      - queue: mongo-messages
        routing_key: "*.storemongo.*"
#  - name: hub_logs
#    type: topic
#    durable: true
#    auto_delete: false
#    bindings:
#      - queue: hub-warn-logs
#        routing_key: "#.warn.#"
#      - queue: hub-error-logs
#        routing_key: "#.error.#"
#      - queue: hub-info-logs
#        routing_key: "#.info.#"