queues:
  - name: mongo-messages
    type: standard
    max_size: 100
    passive: false
    durable: true
    auto_delete: false
    exclusive: false
    no_wait: false
    arguments: { }

  - name: hub-warn-logs
    type: standard
    max_size: 100
    passive: false
    durable: true
    auto_delete: false
    exclusive: false
    no_wait: false
    arguments: {}

  - name: hub-error-logs
    type: standard
    max_size: 100
    passive: false
    durable: true
    auto_delete: false
    exclusive: false
    no_wait: false
    arguments: {}

  - name: hub-info-logs
    max_size: 100
    passive: false
    durable: true
    auto_delete: false
    exclusive: false
    no_wait: false
    arguments: {}

  - name: alerts
    max_size: 100
    passive: false
    durable: true
    auto_delete: false
    exclusive: false
    no_wait: false
    arguments: {}