queues:
# =================================
# LOG QUEUES
# =================================
  - name: hub-warn-logs
    type: standard
    max_size: 100
    passive: false
    durable: true
    auto_delete: false
    exclusive: false
    no_wait: false
    arguments: {}

  - name: hub-error-logs
    type: standard
    max_size: 100
    passive: false
    durable: true
    auto_delete: false
    exclusive: false
    no_wait: false
    arguments: {}

  - name: hub-info-logs
    max_size: 100
    passive: false
    durable: true
    auto_delete: false
    exclusive: false
    no_wait: false
    arguments: {}

# =================================
# ALERT QUEUES
# =================================
  - name: information_alerts
    max_size: 100
    passive: false
    durable: true
    auto_delete: false
    exclusive: false
    no_wait: false
    arguments: {}

  - name: warning_alerts
    max_size: 100
    passive: false
    durable: true
    auto_delete: false
    exclusive: false
    no_wait: false
    arguments: { }

  - name: critical_alerts
    max_size: 100
    passive: false
    durable: true
    auto_delete: false
    exclusive: false
    no_wait: false
    arguments: { }

# =================================
# VIDEO STREAM QUEUES
# =================================
  - name: videostream
    max_size: 100
    passive: false
    durable: true
    auto_delete: false
    exclusive: false
    no_wait: false
    arguments: { }

# =================================
# TEMP WORK IN PROGRESS QUEUES
# =================================
#  - name: mongo-messages
#    type: standard
#    max_size: 100
#    passive: false
#    durable: true
#    auto_delete: false
#    exclusive: false
#    no_wait: false
#    arguments: { }
#
#  - name: notifications
#    max_size: 100
#    passive: false
#    durable: true
#    auto_delete: false
#    exclusive: false
#    no_wait: false
#    arguments: {}
#
#  - name: notifications_critical
#    max_size: 100
#    passive: false
#    durable: true
#    auto_delete: false
#    exclusive: false
#    no_wait: false
#    arguments: {}

exchanges:
  - name: smartess.alert
    type: topic
    durable: true
    auto_delete: false
    bindings:
      - queue: information_alerts
        routing_key: "information.alerts.*"
      - queue: warning_alerts
        routing_key: "warning.alerts.*"
      - queue: critical_alerts
        routing_key: "critical.alerts.*"

  - name: smartess.videostream
    type: direct
    durable: true
    auto_delete: false
    bindings:
      - queue: videostream
        routing_key: "video.stream"

# =================================
# TEMP WORK IN PROGRESS EXCHANGES
# =================================
#  - name: smartess_topic_exchange
#    type: topic
#    durable: true
#    auto_delete: false
#    bindings:
#      - queue: alerts
#        routing_key: "#.alerts.*"
#      - queue: system_alerts
#        routing_key: "system.alerts.*"
#      - queue: notifications
#        routing_key: "#.notifications.*"
#      - queue: notifications_critical
#        routing_key: "#.notifications.critical.*"
#      - queue: mongo-messages
#        routing_key: "*.storemongo.*"
#  - name: hub_logs
#    type: topic
#    durable: true
#    auto_delete: false
#    bindings:
#      - queue: hub-warn-logs
#        routing_key: "#.warn.#"
#      - queue: hub-error-logs
#        routing_key: "#.error.#"
#      - queue: hub-info-logs
#        routing_key: "#.info.#"
#
#
#      - queue: system_alerts
#        routing_key: "system.alerts.*"
#      - queue: notification_alerts
#        routing_key: "notification.alerts.*"
#      - queue: audio_alerts
#        routing_key: "audio.alerts.*"
#      - queue: visual_alerts
#        routing_key: "visual.alerts.*"
#      - queue: log_alerts
#        routing_key: "log.alerts.*"
#      - queue: actionable_alerts
#        routing_key: "actionable.alerts.*"
#
#
#      - name: system_alerts
#        max_size: 100
#        passive: false
#        durable: true
#        auto_delete: false
#        exclusive: false
#        no_wait: false
#        arguments: { }
#
#      - name: notification_alerts
#        max_size: 100
#        passive: false
#        durable: true
#        auto_delete: false
#        exclusive: false
#        no_wait: false
#        arguments: { }
#
#      - name: audio_alerts
#        max_size: 100
#        passive: false
#        durable: true
#        auto_delete: false
#        exclusive: false
#        no_wait: false
#        arguments: { }
#
#      - name: visual_alerts
#        max_size: 100
#        passive: false
#        durable: true
#        auto_delete: false
#        exclusive: false
#        no_wait: false
#        arguments: { }
#
#      - name: log_alerts
#        max_size: 100
#        passive: false
#        durable: true
#        auto_delete: false
#        exclusive: false
#        no_wait: false
#        arguments: { }
#
#      - name: actionable_alerts
#        max_size: 100
#        passive: false
#        durable: true
#        auto_delete: false
#        exclusive: false
#        no_wait: false
#        arguments: { }
#
#  {
#    "routing_key": "normal.alerts.test",
#    "content": "{\"message\": \"normal alert\"}"
#  },
#  {
#    "routing_key": "system.alerts.test",
#    "content": "{\"message\": \"system alert\"}"
#  },
#  {
#    "routing_key": "notification.alerts.test",
#    "content": "{\"message\": \"notification alert\"}"
#  },
#  {
#    "routing_key": "audio.alerts.test",
#    "content": "{\"message\": \"audio alert\"}"
#  },
#  {
#    "routing_key": "visual.alerts.test",
#    "content": "{\"message\": \"visual alert\"}"
#  },
#  {
#    "routing_key": "log.alerts.test",
#    "content": "{\"message\": \"log alert\"}"
#  },
#  {
#    "routing_key": "actionable.alerts.test",
#    "content": "{\"message\": \"actionable alert\"}"
#  }