queues:
  - name: generic-messages
    type: standard
    max_size: 100
    passive: false
    durable: true
    auto_delete: false
    exclusive: false
    no_wait: false
    arguments: {}
    message_format:
      type: json
      schema:
          id: integer          # ID of the sender (HubID)
          json: string         # The message content (Content)
          time_fired: string   # Timestamp for when the message was created (TimeStamp)
  - name: hub-info-logs
    type: standard
    max_size: 100
    passive: false
    durable: true
    auto_delete: false
    exclusive: false
    no_wait: false
    arguments: {}
    message_format:
      type: json
      schema:
          message: string
          time_fired: string
  - name: hub-warn-logs
    type: standard
    max_size: 100
    passive: false
    durable: true
    auto_delete: false
    exclusive: false
    no_wait: false
    arguments: {}
    message_format:
      type: json
      schema:
          message: string
          time_fired: string
  - name: hub-error-logs
    type: standard
    max_size: 100
    passive: false
    durable: true
    auto_delete: false
    exclusive: false
    no_wait: false
    arguments: {}
    message_format:
      type: json
      schema:
          message: string
          time_fired: string
