global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'rabbitmq'
    static_configs:
      - targets: ['rabbitmq:15672'] # Scrape RabbitMQ management endpoint
    metrics_path: /metrics
    scheme: http
    basic_auth:
      username: admin
      password: admin # RabbitMQ credentials
