version: '3.7'

services:
  mockhub:
    container_name: mockhub
    build:
      context: ../../../go
      dockerfile: cmd/mockhub/Dockerfile  # Specify the Dockerfile path relative to the build context
    environment:
      - HUB_IP=mockhub:8765 # temporary hub_ip value for easier logging (logging set up for real hub)
    ports:
      - "8765:8765"
    volumes:
      - ./data:/tmp/data
    networks:
      - smartess_network
  mock_camera:
    container_name: mock_camera
    build:
      context: ../../../go/cmd/mock_camera
    ports:
      - "8554:8554"
    healthcheck:
      test: [ "CMD", "ffmpeg", "-i", "rtsp://mock_camera:8554/live", "-t", "1", "-f", "null", "/dev/null" ]
      interval: 30s
      retries: 5
      start_period: 10s
      timeout: 5s
    networks:
      - smartess_network
networks:
  smartess_network:
    external: true