import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import DashboardNavbar from "./DashboardNavbar"; // Import the navbar
import { ReactNode } from "react";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Smartess",
  description: "Generated by create next app",
};

interface DashboardProps {
  children: ReactNode;
}

const RootLayout = ({ children }: DashboardProps) => {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
          <DashboardNavbar />
          <main className="min-h-screen py-10 lg:pl-72">{children}</main>
      </body>
    </html>
  );
}

export default RootLayout;