#Build stage

FROM node:22-alpine3.19 AS build

WORKDIR /src
COPY package.json .
RUN npm install
COPY . .

RUN npm run build

# Production stage
FROM node:22-alpine3.19 AS production

WORKDIR /app

COPY --from=build /src/.next ./.next
COPY --from=build /src/node_modules ./node_modules
COPY --from=build /src/package.json ./package.json
#COPY --from=build /src/public ./public

CMD npm start