version: '3.7'

services:

  mock-mongo-server:
    container_name: mock-mongo-server
    build:
      context: ../../../go
      dockerfile: cmd/mock_mongo_server/Dockerfile
    volumes:
      - ./logs:/app/logs
      - ../../common/configs:/app/config
    ports:
      - "9090:9090"
    networks:
      - smartess_network
networks:
  smartess_network:
    external: true