linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - gosimple
    - unused
    - ineffassign
    - gofmt
    - goimports

run:
  timeout: 5m
  tests: true
  modules-download-mode: vendor # Check workflows/go-ci.yaml for module validation and vendoring
#  skip-dirs-use-default: true
  skip-dirs:
    - /usr/local/go/src
    - /opt/hostedtoolcache/go
    - C:/Program Files/Go/src
issues: # NB: max-issues and max-same thresholds do not apply on Github Actions, which limit 10 issues max on their UI
  exclude-use-default: false
  max-issues-per-linter: 0 #3
  max-same-issues: 0 #1
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
    - path: ".*"
      text: "composites: go.mongodb.org/mongo-driver/bson/primitive.E struct literal uses unkeyed fields"
      linters:
        - govet
linters-settings: # NB: errcheck is disabled for logger functions since our logger is usually used alongside other handling already
  errcheck:
    exclude-functions:
      - (*Smartess/go/hub/logger.Logger).Error
      - (*Smartess/go/hub/logger.Logger).Info
      - (*Smartess/go/hub/logger.Logger).Warn
      - (*Smartess/go/hub/logger.Logger).Fatal
      - (*github.com/gorilla/websocket.Conn).Close
      - (*github.com/streadway/amqp.Channel).Close
      - (*github.com/streadway/amqp.Connection).Close
