linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - gosimple
    - unused
    - structcheck
    - varcheck
    - deadcode
    - ineffassign
    - gofmt
    - goimports

run:
  timeout: 5m
  tests: true

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck