import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const sequelSans = localFont({
  src: [
    {
      path: "../public/fonts/Sequel-Sans-Medium-Body.ttf",
      weight: "400",
    },
    {
      path: "../public/fonts/Sequel-Sans-Medium-Body.ttf",
      weight: "700",
    },
  ],
  variable: "--font-sequel-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${sequelSans.variable} font-sans`}>{children}</body>
    </html>
  );
}
