# Use the Nginx base image to serve static files
FROM nginx:alpine

# Copy the frontend code into the container
COPY . /usr/share/nginx/html

# Expose port 80 to serve the frontend via HTTP
EXPOSE 80
