auth_enabled: false

server:
  http_listen_port: 3100
  log_level: info
  grpc_listen_port: 9095

ingester:
  lifecycler:
    address: 127.0.0.1
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1
    final_sleep: 0s

limits_config:
  reject_old_samples: true
  reject_old_samples_max_age: 168h
  allow_structured_metadata: false  # You can keep this if you're temporarily disabling validation

schema_config:
  configs:
    - from: 2024-10-22  # Use the current date
      store: tsdb
      object_store: filesystem
      schema: v13
      index:
        prefix: index_
        period: 24h

storage_config:
  tsdb_shipper:
    active_index_directory: /loki/index  # Set the active index directory
    cache_location: /loki/cache  # Set the cache location
  filesystem:
    directory: /loki/chunks

common:
  path_prefix: /loki  # Specify a path prefix for tsdb

compactor:
  working_directory: /loki/compactor

table_manager:
  retention_deletes_enabled: true
  retention_period: 336h
